// Mocks generated by Mockito 5.0.15 from annotations
// in restaurant_apps/test/api_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:restaurant_apps/api/api_service.dart' as _i5;
import 'package:restaurant_apps/model/restaurant_details.dart' as _i3;
import 'package:restaurant_apps/model/restaurant_list_model.dart' as _i2;
import 'package:restaurant_apps/model/restaurant_search_model.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeRestaurantsListModel0 extends _i1.Fake
    implements _i2.RestaurantsListModel {}

class _FakeRestaurantDetailModel1 extends _i1.Fake
    implements _i3.RestaurantDetailModel {}

class _FakeRestoSearchModel2 extends _i1.Fake implements _i4.RestoSearchModel {}

/// A class which mocks [ApiServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServices extends _i1.Mock implements _i5.ApiServices {
  MockApiServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.RestaurantsListModel> allRestaurantList() =>
      (super.noSuchMethod(Invocation.method(#allRestaurantList, []),
              returnValue: Future<_i2.RestaurantsListModel>.value(
                  _FakeRestaurantsListModel0()))
          as _i6.Future<_i2.RestaurantsListModel>);
  @override
  _i6.Future<_i3.RestaurantDetailModel> restoDetail(String? id) =>
      (super.noSuchMethod(Invocation.method(#restoDetail, [id]),
              returnValue: Future<_i3.RestaurantDetailModel>.value(
                  _FakeRestaurantDetailModel1()))
          as _i6.Future<_i3.RestaurantDetailModel>);
  @override
  _i6.Future<_i4.RestoSearchModel> restoSearch(String? query) =>
      (super.noSuchMethod(Invocation.method(#restoSearch, [query]),
              returnValue:
                  Future<_i4.RestoSearchModel>.value(_FakeRestoSearchModel2()))
          as _i6.Future<_i4.RestoSearchModel>);
  @override
  String toString() => super.toString();
}
